# Generated by Django 2.1.3 on 2018-11-28 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.TextField(max_length=400)),
                ('rent_days', models.IntegerField(default=1)),
                ('quality', models.IntegerField(default=1)),
                ('brand', models.CharField(max_length=50)),
                ('taken', models.BooleanField()),
                ('price', models.FloatField(default=0.01)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
