# Generated by Django 2.1.3 on 2018-12-05 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20181130_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='comments',
        ),
        migrations.AddField(
            model_name='direction',
            name='code_zip',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='rent',
            name='comments',
            field=models.TextField(default=22, max_length=180),
            preserve_default=False,
        ),
    ]
