# Generated by Django 2.1.3 on 2018-12-07 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20181204_1942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rent',
            old_name='comments',
            new_name='comment',
        ),
    ]
